// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ProvenStyle.DemoWebApi.DataMigrations.Migrations
{
    public sealed partial class updatingPerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatingPerson));
        
        string IMigrationMetadata.Id
        {
            get { return "201309220501041_updatingPerson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
