// <auto-generated />
namespace ProvenStyle.DemoWebApi.DataMigrations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class personNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(personNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201311022118194_personNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
