// <auto-generated />
namespace ProvenStyle.DemoWebApi.DataMigrations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class instructor2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(instructor2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311241953473_instructor2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
